#!/bin/sh
# Make sure this file is executable with chmod +x filename
# Run this script with sudo /path/to/file
# Need to add latex install part & hyperfine

# Essential
sudo pacman -S git
sudo pacman -S curl
sudo pacman -S nvim
sudo pacman -S python
sudo pacman -S python-pip

# Dependencies for coc and its extentsions
sudo pacman -S nodejs
pip install pynvim
pip install black

# Nvim dotfiles included
git clone "https://github.com/Rido-o/dotfiles.git" $HOME

# Install plug
wget -xO $HOME/.local/share/nvim/site/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

#nvim +PlugInstall +qall # If other plug install doesn't work use this
nvim --headless +PlugInstall +qall # Install plugins in the background
