#!/bin/sh

while read file
do
	case "$1" in
		"w") cp "$file" "$HOME/.cache/wallpaper.png" && set-wallpaper ;;
		"l") sudo cp "$file" "/usr/share/pixmaps/wallpaper.png" ;;
		"p") cp "$file" "$HOME/.cache/wallpaper.png" && set-wallpaper && color-dark-pywal ;;
		"P") cp "$file" "$HOME/.cache/wallpaper.png" && set-wallpaper && color-light-pywal ;;
		"r") qutebrowser "https://yandex.com/images/search?source=collections&rpt=imageview&url=$file" ;;
	esac
done
