#!/bin/sh

# Private dot file install
git clone --bare https://github.com/Rido-o/dotfiles.git $HOME/.cfg/dotfiles
# enter github login details
/usr/bin/git --git-dir=$HOME/.cfg/dotfiles-private --work-tree=$HOME $@ checkout
/usr/bin/git --git-dir=$HOME/.cfg/dotfiles-private --work-tree=$HOME $@ config status.showUntrackedFiles no
