#!/bin/bash

# In route directory of a fresh install as a modded user

# Manual command to begin installation
# sh <(wget -qO- https://raw.githubusercontent.com/Rido-o/dotfiles/master/.cfg/install/install)

# ----------------------------------------------------------------

# Update package list
sudo pacman -Sy
sudo pacman -S --noconfirm git
sudo pacman -S archlinux-keyring

# Dot file install
git clone --bare https://github.com/Rido-o/dotfiles.git $HOME/.cfg/dotfiles
/usr/bin/git --git-dir=$HOME/.cfg/dotfiles --work-tree=$HOME $@ checkout
/usr/bin/git --git-dir=$HOME/.cfg/dotfiles --work-tree=$HOME $@ config status.showUntrackedFiles no

# Install AUR helper
sudo git clone https://aur.archlinux.org/yay.git /opt/yay
sudo chown -R mrbones:users /opt/yay
(cd /opt/yay && makepkg --noconfirm -si)

# Pacman list
pacList=("zsh" "zsh-syntax-highlighting" "zsh-autosuggestions" # Install zsh and extenstions
	 "dash" # Install dash
	 "man-db" "man-pages" "texinfo" "most" # Install support for man pages
	 "xorg-xinit" "xorg" "xclip" "xdg-user-dirs" # Install Xorg and other utilties
	 "neovim" "python" "python-pip" "nodejs" "npm" "hyperfine" "unzip" "stylua"# Install Nvim and related utilities
	 "pulseaudio" "pamixer" "pulsemixer" # Install audio
	 "mpd" "mpc" "ncmpcpp" # Install music player
	 "imlib2" # Install slock dependency
	 "curl" "ffmpeg" "dunst" "network-manager-applet" # Install dwm statusbar dependencies
	 "fortune-mod" "cowsay" "xautolock" # Install slock autolock script dependencies
	 "zathura" "zathura-pdf-mupdf" "xwallpaper" "newsboat" "picom" "mpv" "z" "youtube-dl" "sd" "fd" # Installing misc
	 "exiv2" "imagemagick" # Install exiv2 and imagemagick for image dimensions in sxiv statusbar # Might not be needed anymore
	 "fzf" # Used in nnn # Used in nvim with telescope
	 "cronie" # Install cronie
	 "glib2" # Fixes libpango symbol lookup errors
	 "reflector" # Used for updating mirrorlist
	 "ripgrep" # Grep replacement
	 "transmission-cli" # Torrent daemon
	 "python-adblock" # Adblock for qutebrowser
	 "lightdm" "lightdm-gtk-greeter" "light-locker" # Display manager and screen locker
	 "qutebrowser" # Web browser
	 "python-pywal" # Colorscheme generator
	 "ibus" "ibus-anthy" # Japanese language support
	 "pyright" # Python LSP for use with nvim
     "lazygit" # Git interface
	 "bitwarden" "bitwarden-cli" # Installing bitwarden
     "noto-fonts" # noto-fonts-emoji noto-fonts-cjk noto-fonts-extra # Fixes fonts being incorrect with kochi
     "libexif" # nsxiv dependency
	)

yayList=("dashbinsh" # Used to make sure dash remains as /bin/sh # might need to link dash as /bin/sh first
	 "cozette-otb" "nerd-fonts-hack" "ttf-kochi-substitute" # ttf-google-fonts-git # Install fonts, ttf-kochi-substitute fixes missing icons for cozette but fucks up fonts everywhere else
	 "gotop-bin" "networkmanager-dmenu-git" # Install dwm statusbar dependencies
	 "stig" # or transmission-remote-cli-git # Tui transmission client
	 "fvwm" # A window manager
	)

pipList=("pynvim" "black" # Used together with nvim
	 "ueberzug" # Used for album art support in ncmpcpp
	 # "tldextract" # Related to bitwarden # Not sure if still necessary
	 "trash-cli" # Used in nnn # arch repo has old as fuck build
	)

# Install Packages
sudo pacman -S --noconfirm "${pacList[@]}"
yay -S --answerdiff None --answerclean ALL --noconfirm "${yayList[@]}"
pip install "${pipList[@]}"

# Git clone
git clone https://github.com/alnj/ncmpcpp-ueberzug.git $HOME/.config/ncmpcpp/ncmpcpp-ueberzug
git clone https://github.com/Rido-o/st.git $HOME/.local/src/st
git clone https://github.com/Rido-o/dmenu.git $HOME/.local/src/dmenu
git clone https://github.com/Rido-o/dwmblocks.git $HOME/.local/src/dwmblocks
git clone https://github.com/Rido-o/dwm-flexipatch.git $HOME/.local/src/dwm-flexipatch
git clone https://github.com/dylanaraps/pfetch.git $HOME/.local/src/pfetch
git clone https://github.com/Rido-o/xmenu.git $HOME/.local/src/xmenu
git clone https://github.com/Rido-o/nsxiv.git $HOME/.local/src/nsxiv
git clone https://github.com/jarun/nnn.git $HOME/.local/src/nnn
git clone https://github.com/EliverLara/Nordic.git $HOME/.themes/Nordic # Install gtk theme

# Make install
sudo make clean install -C $HOME/.local/src/st
sudo make clean install -C $HOME/.local/src/dmenu
sudo make clean install -C $HOME/.local/src/dwmblocks
sudo make clean install -C $HOME/.local/src/dwm-flexipatch
sudo make install-all -C $HOME/.local/src/nsxiv
sudo make install -C $HOME/.local/src/pfetch
sudo make install -C $HOME/.local/src/xmenu
sudo make install O_NERD=1 -C $HOME/.local/src/nnn

# Install Zsh
mkdir -p $HOME/.cache/zsh && touch $HOME/.cache/zsh/history
sudo chsh -s /usr/bin/zsh $(whoami)

# Install dash as #!/bin/sh
sudo ln -sfT dash /usr/bin/sh

# Install Nvim
#mkdir -p $HOME/.cache/nvim/undodir
#mkdir -p $HOME/.local/share/nvim/site/autoload
#wget -xO $HOME/.local/share/nvim/site/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
#nvim --headless +PlugInstall +qall

# Install cover art support for ncmpcpp # Move to after git clone
chmod +x $HOME/.config/ncmpcpp/ncmpcpp-ueberzug/ncmpcpp-ueberzug $HOME/.config/ncmpcpp/ncmpcpp-ueberzug/ncmpcpp_cover_art.sh
patch $HOME/.config/ncmpcpp/ncmpcpp-ueberzug/ncmpcpp_cover_art.sh $HOME/.cfg/install/patches/ncmpcpp-ueberzug-settings.diff
rm $HOME/.config/ncmpcpp/ncmpcpp-ueberzug/ncmpcpp_cover_art.sh.orig

# Installing browser # Import 4chanX and OneeChan settings manually in ~/.cfg/install/settings
wget -P $HOME/.config/qutebrowser/greasemonkey https://www.4chan-x.net/builds/4chan-X.user.js
wget -P $HOME/.config/qutebrowser/greasemonkey https://raw.githubusercontent.com/KevinParnell/OneeChan/master/builds/OneeChan.user.js

# Installing bitwarden # Manually login to bw with bw login to use keybinds in qutebrowser
sudo patch /usr/share/qutebrowser/userscripts/qute-bitwarden $HOME/.cfg/install/patches/qute-bitwarden-dmenu.diff
sudo rm /usr/share/qutebrowser/userscripts/qute-bitwarden.orig

# Install umpv script
wget -P $HOME/.local/bin https://raw.githubusercontent.com/mpv-player/mpv/master/TOOLS/umpv
patch $HOME/.local/bin/umpv $HOME/.cfg/install/patches/umpv-socket-location.diff
rm $HOME/.local/bin/umpv.orig
chmod +x $HOME/.local/bin/umpv

# Install nsxiv-rifle script
wget -P $HOME/.local/bin https://raw.githubusercontent.com/nsxiv/nsxiv-extra/master/scripts/nsxiv-rifle/nsxiv-rifle
sudo chmod +x $HOME/.local/bin/nsxiv-rifle # strange that this requires sudo

# Install nnn plugins
wget -O - https://raw.githubusercontent.com/jarun/nnn/master/plugins/getplugs | sh

# Install cronie
sudo systemctl enable cronie
crontab $HOME/.cfg/install/extras/cronjobs

# Install lightdm
sudo cp "$HOME/.cfg/install/extras/wallpaper.png" "/usr/share/pixmaps/wallpaper.png"
sudo cp "$HOME/.cfg/install/extras/wallpaper.png" "$HOME/.config/wallpaper.png"
sudo cp $HOME/.cfg/install/extras/lightdm.conf /etc/lightdm/lightdm.conf
sudo cp $HOME/.cfg/install/extras/lightdm-gtk-greeter.conf /etc/lightdm/lightdm-gtk-greeter.conf
sudo cp $HOME/.cfg/install/extras/lightdmxrandr /usr/share/lightdmxrandr
sudo cp $HOME/.cfg/install/extras/dwm.desktop /usr/share/xsessions/dwm.desktop
sudo cp -r $HOME/.themes/Nordic /usr/share/themes/
sudo systemctl enable lightdm

# Remove uneeded files
rm $HOME/.bash_history $HOME/.bash_profile $HOME/.bash_logout $HOME/.bashrc $HOME/.npmrc $HOME/.wget-hsts
rm -r $HOME/.pkg-cache $HOME/.nvm $HOME/Desktop $HOME/Music $HOME/Public $HOME/Templates
#yay -Yc --noconfirm # clean uneeded dependencies used by yay

# Creating root folder tree structure
mkdir Adult Archives Audio Audio/Music Audio/Web/Youtube Documents Downloads Education Games Literature Images Images/Screenshots Images/Wallpapers/Desktop-Wallpapers Projects Video Video/Web/Youtube Work

# Run a theme?
# Follow manual settings

reboot
